config/routes.rb
Eshop::Application.routes.draw do
  resources :variant_option_type_values do as_routes end

  resources :variant_option_types do as_routes end

  resources :tags
  
  resources :products do
     resources :variants do
        post 'add', :on => :collection
     end
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/variant.rb
class Variant < ActiveRecord::Base
  attr_accessible :code
  belongs_to :product
end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
  # GET /products/1/variants
  # GET /products/1/variants.json
  def index
    @variants = Variant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @variants }
    end
  end

  # GET /variants/1
  # GET /variants/1.json
  def show
    @variant = Variant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @variant }
    end
  end

  # GET /variants/new
  # GET /variants/new.json
  def new
    
    @product = Product.find(params[:product_id])
    @variant = @product.variants.build

    
    #@variant = Variant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @variant }
    end
  end

  # GET /variants/1/edit
  def edit
    @variant = Variant.find(params[:id])
  end
 
 
  # POST /variants
  # POST /variants.json
  def create

    @product = Product.find(params[:product_id])
    @variant = @product.variants.create(params[:variant])

    respond_to do |format|
      if @variant.save
        format.html { redirect_to product_variant_path(@variant.product, @variant), :notice => 'Variant was successfully created.' }
        format.json { render json: @variant, status: :created, location: @variant }
      else
        logger.info("Validation failed on new variant")

        format.html { render action: "new" }
        format.json { render json: @variant.errors, status: :unprocessable_entity }

      end

    end

  end

  #Adds variants to the product
  def add
     logger.info("Calling ADD")
     @product = Product.find(params[:product_id])
     
     params[:variant_option_values].each do |vov|
        variant = @product.variants.create(:code=>vov)
        variant.save  
     end          
     redirect_to product_path(@product)
  end


  # PUT /variants/1
  # PUT /variants/1.json
  def update
    @variant = Variant.find(params[:id])

    respond_to do |format|
      if @variant.update_attributes(params[:variant])
        logger.info("Updating variant")
        format.html { redirect_to product_variant_path(@variant.product, @variant), :notice => 'Variant was successfully updated.' }
        format.json { head :no_content }
      else
        logger.info("Updating failed")
        format.html { render action: "edit" }
        format.json { render json: @variant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variants/1
  # DELETE /variants/1.json
  def destroy
    @product = Product.find(params[:product_id])
    @variant = Variant.find(params[:id])
    @variant.destroy

    respond_to do |format|
      format.html {redirect_to product_path(@product)}
      format.json { head :no_content }
    end
  end
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/variants/_form.html.erb
<%= form_for([@variant.product,@variant]) do |f| %>
  <% if @variant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@variant.errors.count, "error") %> prohibited this variant from being saved:</h2>

      <ul>
      <% @variant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/variants/_variants_table.html.erb
<table>
  <tr>
    <th>Code</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% if variants!=nil%>
<% variants.each do |variant| %>
  <tr>
    <td><%= variant.code %></td>
    <td><%= link_to 'Show', product_variant_path(variant.product,variant) %></td>
    <td><%= link_to 'Edit', edit_product_variant_path(variant.product,variant) %></td>
    <td><%= link_to 'Destroy', product_variant_path(variant.product,variant), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
<% end %>
</table>

app/views/variants/edit.html.erb
<h1>Editing variant</h1>

<%= render 'form' %>

<%= link_to 'Show', product_variant_path %> |
<%= link_to 'Back', product_variant_path %>

app/views/variants/index.html.erb
<h1>Listing variants</h1>

<%= render :partial => "variants_table", :locals => {:variants => @variants} %>

<br />

<%= link_to 'New Variant', new_variant_path %>

app/views/variants/new.html.erb
<h1>New variant</h1>

<%= render 'form' %>

<%= link_to 'Back', product_path(@product) %>

app/views/variants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @variant.code %>
</p>


<%= link_to 'Edit', edit_product_variant_path(@variant.product, @variant) %>
<%= link_to 'Back', product_path(@variant.product) %>