config/routes.rb
Eshop::Application.routes.draw do
  resources :variant_option_type_values do as_routes end

  resources :variant_option_types do as_routes end

  resources :tags
  
  resources :products do
     resources :variants do
        post 'add', :on => :collection
     end
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price, :VAT_exempt, :tag_ids, :variant_option_type_ids
  validates :name,  :presence => true
  validates :price,  :presence => true
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :variant_option_types
  has_many :variants
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end


  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    
    @possible_variants = []

    #Create a list of lists for the options
    vot_list = []    
    @product.variant_option_types.each do |vot|
        votv_list = []
        vot.variant_option_type_values.each do |votv|
            votv_list << votv.name
        end
        vot_list << votv_list
    end


 #Create the cross join of all possibilities
    if !vot_list.empty?
      all_variants = vot_list[0].product(*vot_list[1..-1])

      all_variants.each do |v|
        @possible_variants << {:vos=>v, :code=> v*"/"}
      end

    end

    logger.debug "possible_variants="+@possible_variants.to_s          
         
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end



  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end


  # PUT /products/1
  # PUT /products/1.json
  def update
    #if no tags are passed, set to an empty array
    params[:product][:tag_ids] ||= []
    params[:product][:variant_option_type_ids] ||= []
    
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update_attributes(params[:product])
        logger.info("Updating tag_ids="+params[:tag_ids].to_s)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy  

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
 
 <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 
 
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :VAT_exempt %><br />
    <%= f.text_field :VAT_exempt %>
  </div>
  <div class="field">
  <%= f.label :variant_option_types%>
  <% for vot in VariantOptionType.find(:all) %>
  <div>
	<%= check_box_tag "product[variant_option_type_ids][]", vot.id, @product.variant_option_types.include?(vot) %>
	<%= vot.name %>
  </div>
  <% end %>
  </div>


  <div class="field">
  <%= f.label :tags %><br />
  <%= select_tag("product[tag_ids][]", options_for_select(Tag.find(:all).collect{ |tag| [tag.name, tag.id]},
  				@product.tags.collect { |tag| tag.id}),{:multiple=>true}) %>  	
  </div>
    
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Vatexempt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.price %></td>
    <td><%= product.VAT_exempt %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Vatexempt:</b>
  <%= @product.VAT_exempt %>
</p>

<h2>Product varies by</h2>

<% if @product.variant_option_types!=nil%>
<% 	@product.variant_option_types.each do |vot| %>
	<p><%=vot.name%> <em>(shown as <%=vot.display_name%></em>)</p>
<% end %>
<% end %>

<h2>Possible variants</h2>
<%= form_tag add_product_variants_path(@product) do |f| %>
<table>
	<tr>
	
	<% 	@product.variant_option_types.each do |vot| %>		
	<th><%=vot.display_name%></th>
	<% end %>
	
	<th>Select</th>
	</tr>
<% 	@possible_variants.each do |v| %>
<tr>
	<% v[:vos].each do |vo| %>
	<td><%=vo%></td>
	<% end %>
	<td><%= check_box_tag "variant_option_values[]", v[:code] %></td>
</tr>	
<% end %>
</table>
<%= submit_tag 'Add Variants'%>
<% end %>


<h2>Variants</h2>
<%= render :partial => "variants/variants_table", :locals => {:variants => @product.variants} %>


<%= link_to 'New Variant', new_product_variant_path(@product) %>

<%#= link_to 'Edit', edit_product_path(@product) %>
<%= link_to 'Back', products_path %>